# Generated by Django 3.2.7 on 2021-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=3000)),
                ('name', models.CharField(max_length=6000)),
                ('email', models.CharField(max_length=7000)),
                ('address', models.CharField(max_length=1000000)),
                ('city', models.CharField(max_length=50000)),
                ('state', models.CharField(max_length=8000)),
                ('zip_code', models.CharField(max_length=10000)),
            ],
        ),
    ]
