# Generated by Django 3.2.8 on 2021-10-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
