# Generated by Django 3.2.8 on 2021-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
